# Generated by Django 5.0.7 on 2024-08-05 21:49

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("invoice_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "register_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="expenses/", verbose_name="تصویر"),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="نام پروژه"),
                ),
                (
                    "expense_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ پرداخت وجه"),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[("تنخواه", "تنخواه"), ("چک", "چک"), ("سایر", "سایر")],
                        max_length=50,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "expense_method",
                    models.CharField(
                        choices=[("نقد", "نقد"), ("چک", "چک")],
                        max_length=50,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "cash_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ پرداختی",
                    ),
                ),
                (
                    "cash_payer_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="نام پرداخت کننده",
                    ),
                ),
                (
                    "cash_account",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="طرف حساب"
                    ),
                ),
                (
                    "cash_description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "check_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ پرداختی",
                    ),
                ),
                (
                    "check_payer_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="نام پرداخت کننده",
                    ),
                ),
                (
                    "check_account",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="طرف حساب"
                    ),
                ),
                (
                    "check_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ چک"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره چک"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نام بانک"
                    ),
                ),
                (
                    "check_description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "پرداخت وجه",
                "verbose_name_plural": "پرداخت وجه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("invoice_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "register_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="invoices/", verbose_name="تصویر"),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="نام پروژه"),
                ),
                (
                    "invoice_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ فاکتور"),
                ),
                ("account", models.CharField(max_length=200, verbose_name="طرف حساب")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مبلغ"
                    ),
                ),
                (
                    "invoice_reference",
                    models.CharField(max_length=200, verbose_name="شماره فاکتور"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "فاکتور",
                "verbose_name_plural": "فاکتورها",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("invoice_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "register_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="payments/", verbose_name="تصویر"),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="نام پروژه"),
                ),
                (
                    "payment_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ دریافت وجه"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("تنخواه", "تنخواه"),
                            ("حقوق", "حقوق"),
                            ("سایر", "سایر"),
                        ],
                        max_length=50,
                        verbose_name="نوع دریافت",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("نقد", "نقد"), ("چک", "چک")],
                        max_length=50,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "cash_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ دریافتی",
                    ),
                ),
                (
                    "cash_receiver_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="نام دریافت کننده",
                    ),
                ),
                (
                    "cash_description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "check_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="مبلغ دریافتی",
                    ),
                ),
                (
                    "check_payer_name",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="نام پرداخت کننده",
                    ),
                ),
                (
                    "check_account",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="طرف حساب"
                    ),
                ),
                (
                    "check_date",
                    django_jalali.db.models.jDateField(
                        blank=True, null=True, verbose_name="تاریخ چک"
                    ),
                ),
                (
                    "check_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره چک"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نام بانک"
                    ),
                ),
                (
                    "check_description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "دریافت وجه",
                "verbose_name_plural": "دریافت وجه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Rent",
            fields=[
                ("invoice_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "register_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                ("image", models.ImageField(upload_to="rents/", verbose_name="تصویر")),
                (
                    "rent_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ پرداخت"),
                ),
                (
                    "payment_source",
                    models.CharField(
                        choices=[
                            ("تنخواه نقدی", "تنخواه نقدی"),
                            ("چک", "چک"),
                            ("سایر", "سایر"),
                        ],
                        max_length=50,
                        verbose_name="منبع پرداخت",
                    ),
                ),
                (
                    "payer_name",
                    models.CharField(max_length=200, verbose_name="نام پرداخت کننده"),
                ),
                ("account", models.CharField(max_length=200, verbose_name="طرف حساب")),
                ("origin", models.CharField(max_length=200, verbose_name="مبدا")),
                ("destination", models.CharField(max_length=200, verbose_name="مقصد")),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="نام پروژه"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مبلغ"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "کرایه",
                "verbose_name_plural": "کرایه\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Statement",
            fields=[
                ("invoice_number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "register_date",
                    django_jalali.db.models.jDateField(
                        auto_now_add=True, verbose_name="تاریخ ثبت"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="statements/", verbose_name="تصویر"),
                ),
                (
                    "project_name",
                    models.CharField(max_length=200, verbose_name="نام پروژه"),
                ),
                (
                    "statement_date",
                    django_jalali.db.models.jDateField(verbose_name="تاریخ صورت وضعیت"),
                ),
                (
                    "contractor_name",
                    models.CharField(max_length=200, verbose_name="نام پیمانکار"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="مبلغ"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
            ],
            options={
                "verbose_name": "صورت وضعیت",
                "verbose_name_plural": "صورت وضعیت\u200cها",
            },
        ),
    ]
